name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda 1x por dia (00:00 UTC)
  workflow_dispatch:       # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create assets folder
        run: mkdir -p assets

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: luzbelasouza
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/snake.svg assets/snake-dark.svg"
          message: "chore: update snake animation"
          default_author: github_actions
